### ISSUE TITLE
Ambrosium Campfire Causing Server Crashes when player is nearby

### ISSUE THREAD

**Issue by Poseidon6473** [Builderdog841/Ancient-Aether#152]
**Playing the Aetherune modpack; one of the players on my server ventured into the Aether and is near an Ambrosium Campfire block. This is almost immediately crashing the server. I made sure to replicate the issue and can confirm it is only when this player loads in at this location with the block nearby. I've put the crash report below (although only an excerpt), if you need me to give you the full crash report please let me know and I can get it to you. Please let me know what I can do about this if anything.**

> java.lang.ClassCastException: class net.builderdog.ancient_aether.block.utility.AmbrosiumCampfireBlock cannot be cast to class cech12.unlitcampfire.mixinaccess.ICampfireBlockMixin (net.builderdog.ancient_aether.block.utility.AmbrosiumCampfireBlock is in module ancient_aether@0.8.2 of loader 'TRANSFORMER' @14ba7f15; cech12.unlitcampfire.mixinaccess.ICampfireBlockMixin is in module unlitcampfire@1.20.1-1.9.0.1 of loader 'TRANSFORMER' @14ba7f15)
>         at net.minecraft.world.level.block.entity.CampfireBlockEntity.burnsInfinite(CampfireBlockEntity.java:1057) ~[server-1.20.1-20230612.114412-srg.jar%23481!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:itemproductionlib.mixins.json:minecraft/CampfireBlockEntityMixin from mod itemproductionlib,pl:mixin:APP:mixins.unlitcampfire.json:CampfireBlockEntityMixin from mod unlitcampfire,pl:mixin:APP:skilltree.mixins.json:CampfireBlockEntityAccessor from mod skilltree,pl:mixin:A,pl:connector_pre_launch:A}
>         at net.minecraft.world.level.block.entity.CampfireBlockEntity.handler$zie000$unlitcampfire$cookTickProxy(CampfireBlockEntity.java:1161) ~[server-1.20.1-20230612.114412-srg.jar%23481!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:itemproductionlib.mixins.json:minecraft/CampfireBlockEntityMixin from mod itemproductionlib,pl:mixin:APP:mixins.unlitcampfire.json:CampfireBlockEntityMixin from mod unlitcampfire,pl:mixin:APP:skilltree.mixins.json:CampfireBlockEntityAccessor from mod skilltree,pl:mixin:A,pl:connector_pre_launch:A}
>         at net.minecraft.world.level.block.entity.CampfireBlockEntity.m_155306_(CampfireBlockEntity.java:71) ~[server-1.20.1-20230612.114412-srg.jar%23481!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:itemproductionlib.mixins.json:minecraft/CampfireBlockEntityMixin from mod itemproductionlib,pl:mixin:APP:mixins.unlitcampfire.json:CampfireBlockEntityMixin from mod unlitcampfire,pl:mixin:APP:skilltree.mixins.json:CampfireBlockEntityAccessor from mod skilltree,pl:mixin:A,pl:connector_pre_launch:A}
>         at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:689) ~[server-1.20.1-20230612.114412-srg.jar%23481!/:?] {re:classloading,pl:accesstransformer:B,pl:connector_pre_launch:A}
>         at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:782) ~[server-1.20.1-20230612.114412-srg.jar%23481!/:?] {re:classloading,pl:accesstransformer:B,pl:connector_pre_launch:A}
>         at net.minecraft.world.level.Level.m_46463_(Level.java:468) ~[server-1.20.1-20230612.114412-srg.jar%23481!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:twilightforest:cloud,pl:connector_pre_launch:A,re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:cloud,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:cloud,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.clip_replace.MixinLevel from mod valkyrienskies,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.get_entities.MixinLevel from mod valkyrienskies,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.world_border.MixinLevel from mod valkyrienskies,pl:mixin:APP:valkyrienskies-common.mixins.json:world.level.MixinLevel from mod valkyrienskies,pl:mixin:APP:aether.mixins.json:common.accessor.LevelAccessor from mod aether,pl:mixin:APP:citadel.mixins.json:LevelMixin from mod citadel,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:WorldMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:enhancedcelestials.mixins.json:MixinWorld from mod enhancedcelestials,pl:mixin:A,pl:connector_pre_launch:A}
>         at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:351) ~[server-1.20.1-20230612.114412-srg.jar%23481!/:?] {re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin from mod cupboard,pl:mixin:APP:corgilib.mixins.json:MixinServerLevel from mod corgilib,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.shipyard_entities.MixinServerLevel from mod valkyrienskies,pl:mixin:APP:valkyrienskies-common.mixins.json:server.world.MixinServerLevel from mod valkyrienskies,pl:mixin:APP:aether.mixins.json:common.accessor.ServerLevelAccessor from mod aether,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin from mod citadel,pl:mixin:APP:fabric-api-lookup-api-v1.mixins.json:ServerWorldMixin from mod fabric_api_lookup_api_v1,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:ServerWorldMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:mixins.bosses_of_mass_destruction.json:ExplosionMixin from mod bosses_of_mass_destruction,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldAccessor from mod friendsandfoes,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldMixin from mod friendsandfoes,pl:mixin:APP:modulargolems.mixins.json:ServerLevelMixin from mod modulargolems,pl:mixin:APP:ars_elemental.mixins.json:ServerLevelMixin from mod ars_elemental,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld from mod enhancedcelestials,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor from mod create,pl:mixin:A,pl:connector_pre_launch:A}
>         at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[server-1.20.1-20230612.114412-srg.jar%23481!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:saturn.mixins.json:allocations.server_directory.MinecraftServerMixin from mod saturn,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:APP:valkyrienskies-common.mixins.json:server.MixinMinecraftServer from mod valkyrienskies,pl:mixin:APP:fabric-message-api-v1.mixins.json:MinecraftServerMixin from mod fabric_message_api_v1,pl:mixin:APP:phantasm.mixins.json:MinecraftServerMixin from mod phantasm,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin from mod citadel,pl:mixin:APP:connectormod.mixins.json:registries.MinecraftServerMixin from mod connectormod,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:MinecraftServerMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:MinecraftServerMixin from mod fabric_resource_loader_v0,pl:mixin:A,pl:connector_pre_launch:A}
>         at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23481!/:?] {re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:connector_pre_launch:A}

**Comment by Poseidon6473** [comment]
I don't know anything about java btw, so if I'm missing something feel free to let me know.

**Comment by Builderdog841** [comment]
This is a really odd issue, I'll look into it

**Comment by Builderdog841** [comment]
Should be fixed in the next patch
