### ISSUE TITLE
0.8.6+ Crash when loading

### ISSUE THREAD

**Issue by RuafuMan-Obs** [Builderdog841/Ancient-Aether#173]
Since 0.8.6 game will crash when loading with ancient aether
[crashreport-2024-2-16_0.59.45.zip](https://github.com/Builderdog841/Ancient-Aether/files/14299953/crashreport-2024-2-16_0.59.45.zip)

**Comment by Builderdog841** [comment]
Issue on Redux' Side, will be fixed in Redux next update
