### ISSUE TITLE
Crash using Bonemeal with ShetiPhian-Core

### ISSUE THREAD

**Issue by CopperGiraffe** [Builderdog841/Ancient-Aether#175]
Hello there,

Having a StackOverFlow error (and crash) when using bonemeal
Here are the details

Minecraft 1.20.1
Forge 47.2.0
Mods : AncientAether 0.8.8 + ShetiPhian-Core

Here are the logs
https://mclo.gs/wFLOIpN

**Comment by Builderdog841** [comment]
Fixed in the next patch

**Comment by GothCartel** [comment]
Encountered same crash

Minecraft 1.20.1
Forge 47.2.0
AncientAether 0.8.8

at net.builderdog.ancient_aether.block.natural.AncientAetherLogBlock.getToolModifiedState(AncientAetherLogBlock.java:34) ~[ancient_aether-0.8.8.jar%23388!/:0.8.8] {re:classloading}

above message is spammed in crash log
