### ISSUE TITLE
Tags and more 1.20.1 Forge 47.2.7

### ISSUE THREAD

**Issue by Krimatoria** [Builderdog841/Ancient-Aether#177]
1.20.1 Forge 47.2.7

> ancient_aether-0.8.8.jar
> deep_aether-1.20.1-1.0.2.jar
> aether-1.20.1-1.2.0-neoforge.jar
> lost_aether_content-1.20.1-1.2.3.jar
> aether_enhanced_extinguishing-1.20.1-1.0.0-neoforge.jar
> aether_delight_1.0.0_forge_1.20.1.jar

There is a lot there, I have collected everything that related to it. Tags, resources, and so on.
https://gist.github.com/Krimatoria/bddb031fc190f31407ad873e12dfc426 - It's probably easier to watch here
[Ancient Aether Log.txt](https://github.com/Builderdog841/Ancient-Aether/files/14475309/Ancient.Aether.Log.txt)

**Comment by Builderdog841** [comment]
Ah, these are all gonna be fixed in the next patch but still thanks
