### ISSUE TITLE
[Crash] [Mod Compat?] Client crash on breaking sakura log

### ISSUE THREAD

**Issue by muon-rw** [Builderdog841/Ancient-Aether#182]
https://mclo.gs/TogFtRS

Circular reference at ` net.builderdog.ancient_aether.block.natural.AncientAetherLogBlock.getToolModifiedState(AncientAetherLogBlock.java:34) ~[ancient_aether-0.8.8.jar%23531!/:0.8.8] {re:classloading}`, similar to #176?

Mod Version:
Ancient Aether 0.8.8

Note that the behavior of "this happened when I hit a log with an affixed axe" was reported by a player, so take it with a grain of salt. 

I have not tested this in an isolated environment - likely candidates include HT's TreeChop and Apotheosis.

**Comment by Builderdog841** [comment]
0.8.8 had some very outdated Log Stripping Code which would cause a Loop if something unexpected happened, leading to a crash. This is Fixed in the next patch
