### ISSUE TITLE
Missing "New Worldgen" Datapack Option

### ISSUE THREAD

**Issue by Lucipo** [Builderdog841/Ancient-Aether#183]
I noticed that in the latest version of the ancient aether, there is no way to turn off the 1.18-styled generation.

Was support for this removed or out of commission for now? Searched through all the information I could and it just has seemed to have dissapeared. Would like to use this mod alongside redux and deep aether with the original generation.

**Comment by Builderdog841** [comment]
It was removed due to a lot of the mods content being build around it and thus requiring it to properly work (especially stuff like structure or biome gen).

**Comment by Lucipo** [comment]
ah I see thank you. as long as its compatible with other mods (such as valkrum ore generation and redux biomes) then its fine.

**Comment by Builderdog841** [comment]
Yeah there has been a lot of compatibility added recently for that and there's more to come. But yeah it should all work fine (at least it does from my tests)
