### ISSUE TITLE
[1.20.1] [0.8.10] Crash when bonemealing any crop with ShetiPhian Core and Platforms

### ISSUE THREAD

**Issue by killer2gudpl** [Builderdog841/Ancient-Aether#184]
Similar to #176 and #172 I am experiencing a crash when applying bonemeal to any crop whatsoever, on Java 17, Forge 47.2.17 (and possibly others).

I was able to reproduce it with only Ancient Aether (0.8.10), Aether (1.3.1), AeroBlender (1.0.1), TerraBlender (3.0.0.169) Platforms (1.1) and ShetiPhian-Core (1.2) present, with a crash starting to happen once I have added on Platforms and ShetiPhian Core (a dependency for Platforms. I have also looked through stack causing the crash) and I have tried to right click with a bone meal on any planted crop. 

I suppose it is a repeat of the previous issue that is still present in the newer version despite it being supposedly fixed.

Would appreciate any help with this issue.

Thank you!

[latest.log](https://github.com/Builderdog841/Ancient-Aether/files/14858769/latest.log)
[crash-2024-04-03_22.39.03-client.txt](https://github.com/Builderdog841/Ancient-Aether/files/14858770/crash-2024-04-03_22.39.03-client.txt)

**Comment by Builderdog841** [comment]
ah I actually know what the issue is, I'll release a hotfix asap

**Comment by Builderdog841** [comment]
Hotfix should be out now
