### ISSUE TITLE
Title Screen Override config set to "false" not working

### ISSUE THREAD

**Issue by GoatGamerHUN** [Builderdog841/Ancient-Aether#192]
Ancient Aether 0.9.6
![image](https://github.com/Builderdog841/Ancient-Aether/assets/46354254/1277bc18-2de9-4b68-ab89-455d704fdc94)

**Comment by GoatGamerHUN** [comment]
Note: When Config Overrides is set to false, it still doesn't work.

**Comment by Builderdog841** [comment]
You also need to change the Cumulus Config back to "minecraft:minecraft"
