### ISSUE TITLE
0.9.6 Void Death Bug

### ISSUE THREAD

**Issue by Krunchee164** [Builderdog841/Ancient-Aether#194]
in version 0.9.6, if you fall off the islands to go to the overworld, it kills you like falling into the void and doesn't teleport you.

**Comment by Builderdog841** [comment]
What Biome were you in when you fell?

**Comment by Krunchee164** [comment]
it has happened in the elevated caverns, holystone caverns and the frozen caverns

**Comment by Builderdog841** [comment]
Very strange do you have other add-ons installed?

**Comment by Krunchee164** [comment]
yes here are all the mods i have:

-     CullLessLeaves Reforged (Unofficial) (by ccr4ft3r)
-     Awesome Dungeon - Forge (by jtl_elisa)
-     ChoiceTheorem's Overhauled Village (by ChoiceTheorem)
-     Library Ferret - Forge (by jtl_elisa)
-     Nullscape (by Starmute)
-     Zombie Horse Spawn (by Serilum)
-     Artifacts (by ochotonida)
-     Sit (by bl4ckscor3)
-     Let Me Despawn (by frikinjay)
-     YUNG's Better Ocean Monuments (Forge) (by YUNGNICKYOUNG)
-     Endless Biomes (by MadoctheHadoc)
-     Awesome Dungeon Nether edition - Forge (by jtl_elisa)
-     It Takes a Pillage (by izofar)
-     Create Stuff & Additions (by Furti_Two)
-     Create: Connected (by Lysine)
-     Cloth Config API (Fabric/Forge/NeoForge) (by shedaniel)
-     Hearths (by bebebea_loste)
-     Awesome Dungeon Ocean edition - Forge (by jtl_elisa)
-     Placebo (by Shadows_of_Fire)
-     BE Style Wither [Forge/Fabric] (by morimori0317)
-     FastSuite (by Shadows_of_Fire)
-     Enlightend (by lixir)
-     Server Performance - Smooth Chunk Save[Forge/Fabric] (by someaddon)
-     Embeddium/Rubidium Dynamic Lights (by Anthxny)
-     Yeetus Experimentus (by Sunekaer)
-     playerAnimator (by KosmX)
-     Repurposed Structures (Neoforge/Forge) (by telepathicgrunt)
-     Skeleton Horse Spawn (by Serilum)
-     Collective (by Serilum)
-     Resourceful Config (by ThatGravyBoat)
-     Deeper and Darker (by KyaniteMods)
-     Biomes O' Plenty (by Forstride)
-     TerraBlender (Forge) (by TheAdubbz)
-     Cumulus (by TheAetherTeam)
-     Twilight Tweaks (by jodlodi)
-     NetherPortalFix (by BlayTheNinth)
-     YUNG's Better End Island (Forge) (by YUNGNICKYOUNG)
-     Balm (Forge Edition) (by BlayTheNinth)
-     Majrusz's Enchantments (by Majrusz17)
-     Exposure (by mortuusars)
-     Embeddium/Rubidium Extras (by Anthxny)
-     Rubidium (by Asek3)
-     Husk Spawn (by Serilum)
-     Structure Essentials[Forge/Fabric] (by someaddon)
-     Botarium (by CodexAdrian)
-     Dusk[Forge/Fabric] (by someaddon)
-     Twilight Forest: The Lost Blocks (by Kitteh6660)
-     The Aether: Redux (by Zepalesque)
-     Amplified Nether (by Starmute)
-     Better ElderGuardian (by tjibbe1)
-     Nyf's Spiders (by Nyfaria)
-     Radium Reforged (by Asek3)
-     Forge Config Screens [Forge & Fabric] (by Fuzs)
-     Bookshelf (by DarkhaxDev)
-     AI Improvements (by QueenOfMissiles)
-     B.F. End Cities (by Anthxny)
-     Curios API (Forge/NeoForge) (by TheIllusiveC4)
-     Smooth Boot (Reloaded) (by AbdElAziz333)
-     Toast Control (by Shadows_of_Fire)
-     Awesome Dungeon The End edition - Forge (by jtl_elisa)
-     Better Ping Display (by Quintinity)
-     ImmediatelyFast (by RaphiMC)
-     Void Fog (by Tamaized)
-     Ecologics (by SameDifferent)
-     Ender Zoology [Forge & Fabric] (by Fuzs)
-     Enchantment Descriptions (by DarkhaxDev)
-     Controlling (by Jaredlll08)
-     Horse Combat Controls (by pitbox46)
-     AeroBlender (by TeamRazor)
-     Polymorph (Fabric/Forge/Quilt) (by TheIllusiveC4)
-     Dungeon Now Loading 1% (by hexnowloading)
-     Galosphere (by orcinus73)
-     Clumps (by Jaredlll08)
-     YUNG's Better Witch Huts (Forge) (by YUNGNICKYOUNG)
-     YUNG's Extras (Forge) (by YUNGNICKYOUNG)
-     FerriteCore ((Neo)Forge) (by malte0811)
-     Blueprint (by TeamAbnormals)
-     The Twilight Forest (by Benimatic)
-     Enhanced Celestials - Blood, Blue, & Harvest (Super) Moons (by Corgi_Taco)
-     Create (by simibubi)
-     L_Ender 's Cataclysm (by mcl_ender)
-     Polytone (by MehVahdJukaar)
-     Citadel (by sbom_xela)
-     Create Crafts & Additions (by MRHminer)
-     Gardens of the Dead (by ochotonida)
-     Aether: Lost Content Addon (by ModdingLegacy)
-     Wither Skeleton Tweaks (by Shadows_of_Fire)
-     Cave Spider Spawn (by Serilum)
-     InsaneLib (by Insane96)
-     Alex's Mobs (by sbom_xela)
-     Mouse Tweaks (by YaLTeR)
-     Searchables (by Jaredlll08)
-     Golden Days (by thepoeticrainbow)
-     Patchouli (by Vazkii)
-     Deep Dark: Regrowth (by clorobored)
-     Incendium (by Starmute)
-     Nyctophobia (FORGE) (by finallion_13)
-     Regions Unexplored (forge/fabric) (by UHQ_GAMES)
-     Majrusz Library (by Majrusz17)
-     TexTrue's Rubidium Options (by TexTrue)
-     MES - Moog's End Structures (by finndog_123)
-     Create: Steam 'n' Rails (by mattentosh)
-     YUNG's Better Strongholds (Forge) (by YUNGNICKYOUNG)
-     Double Doors (by Serilum)
-     Cosmetic Armor Reworked (by LainMI)
-     YUNG's API (Forge) (by YUNGNICKYOUNG)
-     Better Burning (by DarkhaxDev)
-     Structure Gel API (by ModdingLegacy)
-     AtomicStryker's Infernal Mobs (by atomicstrykergrumpy)
-     Aquaculture 2 (by Shadow)
-     Game Menu Remove GFARB (by morimori0317)
-     AttributeFix (by DarkhaxDev)
-     Model Gap Fix (by MehVahdJukaar)
-     Better Fog (by falling_colud96)
-     Tiny Skeletons [Forge & Fabric] (by Fuzs)
-     The Aether (by TheAetherTeam)
-     Entity Culling Fabric/Forge (by tr7zw)
-     Better Mods Button [Forge] (by Fuzs)
-     YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)
-     Framework (by MrCrayfish)
-     No Resource Pack Warnings Forge (by 1foxy2)
-     The Outer End (by BlueDuckYT)
-     Backpacked (by MrCrayfish)
-     Iron Shulker Boxes (by ProgWML6)
-     Just Enough Items (JEI) (by mezz)
-     FPS Reducer (by bre2el)
-     Geophilic – Vanilla Biome Overhauls (by bebebea_loste)
-     Improved Mobs (Forge) (by flemmli97)
-     Iron's Spells 'n Spellbooks (by Iron431)
-     Default Options (by BlayTheNinth)
-     Lithostitched (by Apollo)
-     Moonlight Lib (by MehVahdJukaar)
-     Uppers (by vadis365)
-     Sound Physics Remastered (by henkelmax)
-     From The Fog (by LunarEclipseStudios)
-     GeckoLib (by Gecko)
-     Explorations (by Buecher_wurm)
-     Medieval Buildings [End Edition] (by Lupin)
-     TenshiLib (Forge) (by flemmli97)
-     ModernFix (by embeddedt)
-     Nether Depths Upgrade (by scouter567)
-     Savage Ender Dragon[Forge/Fabric] (by someaddon)
-     No Chat Reports (by Aizistral)
-     Fix Experience Bug (now with FABRIC and FORGE versions) (by MacTso)
-     fix GPU memory leak[Forge/Fabric] (by someaddon)
-     Boatload (by TeamAbnormals)
-     Caelus API (Forge/NeoForge) (by TheIllusiveC4)
-     Alternate Current (by SpaceWalkerRS)
-     [EMF] Entity Model Features [Fabric & Forge] (by traben_0)
-     Realm RPG: Dragon Wyrms (by nocubeyt)
-     YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)
-     YUNG's Better Jungle Temples (Forge) (by YUNGNICKYOUNG)
-     Cupboard (by someaddon)
-     More Villagers (by SameDifferent)
-     Volcanic Caverns (by f1ashfyre)
-     [ETF] Entity Texture Features - [Fabric & Forge] (by traben_0)
-     Connectivity[Forge/Fabric] (by someaddon)
-     Lionfish API (by mcl_ender)
-     Apothic Attributes (AttributesLib) (by Shadows_of_Fire)
-     WF's Cave Overhaul (by WunderFunct)
-     Deep Aether (by TeamRazor)
-     Better Advancements (by way2muchnoise)
-     More Cave Sounds (by memphis)
-     Resourceful Lib (by ThatGravyBoat)
-     Architectury API (Fabric/Forge/NeoForge) (by shedaniel)
-     Spiders Produce Webs (by Serilum)
-     Monster Plus (by Nitespring)
-     Ender Trigon (by nonamecrackers2)
-     Responsive Shields (by Revvilo)
-     Progressive Bosses (by Insane96)
-     Apotheosis (by Shadows_of_Fire)
-     Additional Structures (by XxRexRaptorxX)
-     Fog Overrides [Forge] (by fabbe50)
-     Iron Chests (by ProgWML6)
-     Better Combat [Fabric & Forge] (by daedelus_dev)
-     Fastload (by StockiesLad)
-     Xaero's World Map (by xaero96)
-     Born in Chaos (by mongoose_artist)
-     Iron Ender Chests (by Iron431)
-     YUNG's Better Nether Fortresses (Forge) (by YUNGNICKYOUNG)
-     Puzzles Lib [Forge & Fabric] (by Fuzs)
-     YUNG's Better Desert Temples (Forge) (by YUNGNICKYOUNG)
-     Ancient Aether (by Builderdog841)
-     CorgiLib (by Corgi_Taco)
-     Better F3 (by chpas_)
-     Better Fps - Render Distance[Forge] (by someaddon)
-     Max Health Fix (by DarkhaxDev)
-     Umbral Skies (by Drullkus)
-     Xaero's Minimap (by xaero96)
-     Stray Spawn (by Serilum)
-

**Comment by Krunchee164** [comment]
this issue also only happens on 0.9.6 because if i downgrade to 0.9.5 it fixes the issue
