### ISSUE TITLE
Deep aether stratus pickaxe doesn't drop valkyrum ore

### ISSUE THREAD

**Issue by MikroChris** [Builderdog841/Ancient-Aether#195]
Idk if it's meant to be that way, but when I mine valyrum ores with my stratus pickaxe from deep aether it doesn't drop the ore, also with all the other deep aether tools

**Comment by MikroChris** [comment]
Also happens with aether gravitation

**Comment by Builderdog841** [comment]
Valkyrum Ore only drops with Divine and Valkyrum Pickaxes, this is intentional
