### ISSUE TITLE
Feature Request: Valkyrum Tools Size Should Reflect Their Range

### ISSUE THREAD

**Issue by 2468cool** [Builderdog841/Ancient-Aether#196]
Hi again! I hope you are doing well. Another idea came to mind recently and thought I would request here.

Request: The Valkyrum tool set should look the size of their range when held.

How I think it could be implemented:
- The easy way (I think): This easy way I think would be to change how big the spites are rendered when held by the player.
- The fun way: Have custom 3D models for the tool set that reflect the range the tools have.

Why I think it should be added: I think it helps with immersion in the game being able to physically see the tools be the size that the reach they have is. It also would help compatibility with mods like Better Combat which override the regular reach of the tools for combat.

If this is something outside of the scope of the mod then that's fine. Either way I hope you have a great day!

**Comment by Builderdog841** [comment]
Hi! It's interesting idea but I don't think ot would translate well into since 3d Tool Models look out of plsce with place with mc's art style and larger tools would generally look out of proportion. I'm also quite fond of the current tools, so yeah that won't be changing.
