### ISSUE TITLE
Ancient aether probably breaks the flawless loot from deep aether

### ISSUE THREAD

**Issue by MikroChris** [Builderdog841/Ancient-Aether#197]
Hi, I've been playing aether and deep aether, and decided to add ancient aether to my modpack, I had to remove my previous aether world, so a new one could generate
But when I went to kill bosses, the weren't dropping any keys, and also trying to get the flawless loot (when you kill a boss without getting damage) they didn't drop anything
Also it only happened in that world, made another and everything was great, hope my world didn't corrupt or something like that :c

**Comment by MikroChris** [comment]
LIttle update, the Dev from deep aether mentioned that could be a problem with deep aether, sorry for the problem

**Comment by Builderdog841** [comment]
Ah no worries
