### ISSUE TITLE
[1.20.1] Holes in Lakes

### ISSUE THREAD

**Issue by Reshy** [Builderdog841/Ancient-Aether#198]
I was testing out the mod and I noticed some strange generation with the Sky Lake biome:

I imagine by default they're all supposed to look like this:
![2024-06-03_03 33 30](https://github.com/Builderdog841/Ancient-Aether/assets/2096384/3ccaa51c-3b44-415c-9620-eb14ac14e23a)

Rather than like this:
![2024-06-03_03 33 23](https://github.com/Builderdog841/Ancient-Aether/assets/2096384/e00fb5b2-0dda-4323-8aa1-167adb241f02)
![2024-06-03_03 36 05](https://github.com/Builderdog841/Ancient-Aether/assets/2096384/7a1ab118-d3fc-4bd7-8d07-e79236a62696)

May be worth looking at doing another pass on how the waterfalls generate so there's less patchiness to it or random gaps.

Also, since I'm talking about this biome, it may be worth doing some sort of foliage/fish pass on the lake itself to make it stand out a bit more, empty lakes with nothing in them feels wrong.
![2024-06-03_03 31 53](https://github.com/Builderdog841/Ancient-Aether/assets/2096384/daa89e29-21e6-43dd-b932-3475410a5835)

**Comment by Builderdog841** [comment]
This isn't fixable at the moment and also isn't really as an issue, fish and more vegetation will come eventually
