### ISSUE TITLE
Bug: Valkyrie Cape Spawning Seems To Be Broken

### ISSUE THREAD

**Issue by 2468cool** [Builderdog841/Ancient-Aether#200]
Hi again! I've got another bug report for you.

I did some testing on singleplayer with silver dungeons and their loot. When I played with just the Aether I was able to find a Valkyrie cape within 3 dungeons. When I added this mod, redux, lost content, and deep aether, I could not find a cape after searching 15 dungeons. I removed ancient aether and was able to find a cape on the second dungeon.,

My guess is that when valkyrie tools and armor was removed from the loot pool of silver dungeons that the cape was accidentally removed from the pool as well.

Have a great day!

**Comment by Builderdog841** [comment]
Fixed in the next patch
