### ISSUE TITLE
Potted Elevatia has no texture

### ISSUE THREAD

**Issue by SimulationOfMario** [Builderdog841/Ancient-Aether#201]
![2024-06-20_13 09 21](https://github.com/Builderdog841/Ancient-Aether/assets/124881638/75d8b018-376b-40ff-af0d-b840e1057b95)

**Comment by Builderdog841** [comment]
Odd, I'll look into it for the nextvpatch

**Comment by SimulationOfMario** [comment]
![Image](https://github.com/user-attachments/assets/1f1cb7c2-8d6c-4565-beaf-928d97f022e6)

AA v0.9.9
