### ISSUE TITLE
1.20.1 Ancient Aether 0.9.7 🔥

### ISSUE THREAD

**Issue by Krimatoria** [Builderdog841/Ancient-Aether#203]
[00:21:37] [Worker-ResourceReload-1/ERROR] [minecraft/TagLoader]: Couldn't read tag list ancient_aether:has_structure/holystone_ruin from ancient_aether:tags/worldgen/biome/has_structure/holystone_ruin.json in data pack builtin/compatibility/deep_aether
--
4003 | java.lang.RuntimeException: No key values in MapLike[{"remove":["deep_aether:golden_grove"]}]
4004 | at com.mojang.serialization.DataResult.lambda$getOrThrow$5(DataResult.java:101) ~[datafixerupper-6.0.8.jar%2379!/:?] {re:mixin}
4005 | at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[datafixerupper-6.0.8.jar%2379!/:?] {}
4006 | at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:93) ~[datafixerupper-6.0.8.jar%2379!/:?] {re:mixin}
4007 | at net.minecraft.tags.TagLoader.m_144495_(TagLoader.java:53) ~[client-1.20.1-20230612.114412-srg.jar%23760!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:connectormod.mixins.json:TagLoaderMixin from mod connectormod,pl:mixin:APP:lmft.mixins.json:TagGroupLoaderMixin from mod lmft,pl:mixin:APP:kubejs-common.mixins.json:TagLoaderMixin from mod kubejs,pl:mixin:A,pl:connector_pre_launch:A}
4008 | at net.minecraft.tags.TagLoader.m_203900_(TagLoader.java:114) ~[client-1.20.1-20230612.114412-srg.jar%23760!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:connectormod.mixins.json:TagLoaderMixin from mod connectormod,pl:mixin:APP:lmft.mixins.json:TagGroupLoaderMixin from mod lmft,pl:mixin:APP:kubejs-common.mixins.json:TagLoaderMixin from mod kubejs,pl:mixin:A,pl:connector_pre_launch:A}
4009 | at net.minecraft.tags.TagManager.m_203920_(TagManager.java:55) ~[client-1.20.1-20230612.114412-srg.jar%23760!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:mixin:APP:fabric-resource-conditions-api-v1.mixins.json:TagManagerLoaderMixin from mod fabric_resource_conditions_api_v1,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:KeyedResourceReloadListenerMixin from mod fabric_resource_loader_v0,pl:mixin:APP:kubejs-common.mixins.json:TagManagerMixin from mod kubejs,pl:mixin:A,pl:connector_pre_launch:A}
4010 | at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?] {}
4011 | at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) ~[?:?] {}
4012 | at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
4013 | at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
4014 | at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {re:mixin,re:computing_frames}
4015 | at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {re:mixin,re:computing_frames}
4016 | at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {re:mixin}

**Comment by Builderdog841** [comment]
Fixed in the next update

**Comment by 7yudinglaopin8** [comment]
We need 1.20.1:/
