### ISSUE TITLE
Insane lag when entering aether dimension

### ISSUE THREAD

**Issue by annalizabeth03** [Builderdog841/Ancient-Aether#204]
Anytime I enter the aether, I experience crazy lag. I can't open the lore book or any other item in my inventory. Trying to leave the aether via JourneyMap warp ends up crashing minecraft, and I have to close it via task manager. 
I am playing a mod called Fantasy Skies. [Here's a clip](https://youtu.be/SxntpaVUvkc) of what happens.

**Comment by Builderdog841** [comment]
I dunno you're playing a massive modpack so I can't pin point it to anything here and I doubt it's Ancient Aether that's causing this

**Comment by Builderdog841** [comment]
I'll also need more information like q spark report for example and also try if this accurs with just Ancient Aether and its dependencies, otherwise I'm closing this for now

**Comment by annalizabeth03** [comment]
got it. I'm very new to playing mods so forgive me if I come off as ignorant- I'll mess around with it and see if I can fix anything.

**Comment by Builderdog841** [comment]
all good
