### ISSUE TITLE
crash when clicking create new world

### ISSUE THREAD

**Issue by LandonsBS** [Builderdog841/Ancient-Aether#206]
[crash-2024-10-06_20.26.04-client.txt](https://github.com/user-attachments/files/17271409/crash-2024-10-06_20.26.04-client.txt)

Everything fixed itself when I removed ancient aether or downgraded the original aether mod to 1.4.2

**Comment by Danmccool** [comment]
The Ancient Aether mod will need to be updated to aether 1.5.0

**Comment by Builderdog841** [comment]
duplicate issue
