### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by PhilTheGreatLOL** [Builderdog841/Ancient-Aether#207]
I decide to play with this mods but game suddenly crashed for use latest version of The Aether & Aether Redux
Aether 1.5.1 & Aether Redux 2.0.18
Crash report detail:
[crash-2024-11-13_17.01.54-client.txt](https://github.com/user-attachments/files/17730440/crash-2024-11-13_17.01.54-client.txt)

**Comment by Builderdog841** [comment]
duplicate issue
