### ISSUE TITLE
Crash when creating a world

### ISSUE THREAD

**Issue by PlatinumBoi03** [Builderdog841/Ancient-Aether#208]
So I have a custom modpack and wanna try out the mod but trying to create a new world is causing this crash. The crash report is saying Ancient Aether is causing it, but I wanna know if this can be fixed without having to remove the mod.
[crash-2024-11-17_11.35.00-client.txt](https://github.com/user-attachments/files/17791782/crash-2024-11-17_11.35.00-client.txt)
[latest.log](https://github.com/user-attachments/files/17791783/latest.log)

**Comment by Yoshiman5551** [comment]
+1

**Comment by Builderdog841** [comment]
duplicate issue
