### ISSUE TITLE
Bug(/feature request i guess?): Sakura moa has a bugged texture when used with The Aether: Redux mod

### ISSUE THREAD

**Issue by MarvelMPH** [Builderdog841/Ancient-Aether#71]
I imagine the reason for this is because Aether Redux changes the moa model (IDK if this counts as an issue or a feature request)
![2023-08-30_22 18 22](https://github.com/Builderdog841/Ancient-Aether/assets/90279606/66a87a21-fb26-42e0-929b-0a36604f311f)
![2023-08-30_22 18 24](https://github.com/Builderdog841/Ancient-Aether/assets/90279606/09fb9e60-a988-4a3b-8e38-806c5285e0e6)
![2023-08-30_22 18 29](https://github.com/Builderdog841/Ancient-Aether/assets/90279606/2620aee2-0484-41d2-9474-323414730725)
![2023-08-30_22 18 30](https://github.com/Builderdog841/Ancient-Aether/assets/90279606/abcc4342-ab38-40ab-8e1e-5ddb405924ad)

**Comment by Builderdog841** [comment]
An issue on Aether Redux Side, I'll report it to it.
