### ISSUE TITLE
crash with my modpack when adding this mod

### ISSUE THREAD

**Issue by Thunderrock424242** [Builderdog841/Ancient-Aether#80]
[latest.log](https://github.com/Builderdog841/Ancient-Aether/files/12775433/latest.log)
when removing it it works fine

**Comment by Builderdog841** [comment]
Do you have the latest version of Aeroblender installed since it doesn't seem like it

**Comment by Builderdog841** [comment]
It seems that you don't have it installed

**Comment by Thunderrock424242** [comment]
I will check

**Comment by Thunderrock424242** [comment]
I do have it installed

**Comment by Thunderrock424242** [comment]
It seems to work now after I downgraded aeroblender

**Comment by Builderdog841** [comment]
strange
