### ISSUE TITLE
Small detail with grass

### ISSUE THREAD

**Issue by Doming3000** [Builderdog841/Ancient-Aether#82]
I think this is where I should report this, I noticed that the Aether Grass texture included in The Aether: Redux mod does not adapt well to some biomes, which gives a somewhat ugly appearance.
![2023-10-13_19 18 08](https://github.com/Builderdog841/Ancient-Aether/assets/82414336/9069013c-8d26-4e6e-899b-076679fb7b19)

**Comment by Builderdog841** [comment]
It's technically Aether Redux fault but because of the Grass Spawning changes made in the upcoming Update there won't be any Aether Redux Grass Spawning in Ancient Aether Biomes
