### ISSUE TITLE
Null pointer "this.f_91074_" is null

### ISSUE THREAD

**Issue by melvinczyk** [Builderdog841/Ancient-Aether#86]
[crash-2023-10-23_19.43.44-client.txt](https://github.com/Builderdog841/Ancient-Aether/files/13092393/crash-2023-10-23_19.43.44-client.txt)

**Comment by melvinczyk** [comment]
this was version 0.7.0

**Comment by Builderdog841** [comment]
Update Aeroblender, you need v1.0.1 since AA v0.7.0 utilizes the new Config System of Aeroblender

**Comment by xaphlactus** [comment]
I had the same problem and I'm on Aeroblender 1.0.1 - throws up a "Resource Reload Failed" even on a fresh minecraft install
