### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by xaphlactus** [Builderdog841/Ancient-Aether#87]
1.20.1 Forge
Game crashes on startup after mods loaded, but after removing Ancient Aether it starts up fine
Ran with bare minimum, all as up-to-date as possible:
![image](https://github.com/Builderdog841/Ancient-Aether/assets/143987816/62b01689-b326-439a-be97-07b76a59e8ce)
[crash log](https://github.com/Builderdog841/Ancient-Aether/files/13125483/crash-2023-10-24_11.16.23-client.txt)
[latest.log](https://github.com/Builderdog841/Ancient-Aether/files/13125494/latest.log)

**Comment by Builderdog841** [comment]
Again, you do not seem to have the latest Aeroblender version. At least when the game crashed

**Comment by xaphlactus** [comment]
that's weird then, because I checked to make sure i had the latest version, and at least the jar file says its the correct version so maybe aeroblender has some incorrect file download on curseforge? I can see if I can find another download somewhere else if that will be the correct version

**Comment by xaphlactus** [comment]
yep alright I quickly tried downloading aeroblender from Modrinth instead and it worked this time, so somehow the curseforge download is wrong, I'll go report it for them to know!
